language: node_js
node_js:
- '6'
before_script:
- npm i -g typescript
- tsc
notifications:
  webhooks:
    secure: kUFq7cQk0OeBjgBb7ixsbIUDOtBhlbDQK0O9ianVtexq6olWXFpdHDDku39c6hJI4wDOpJw/bX147JR7Gj80YZMP1dbKwxVjIcjzfTQXEwj51feDI9+gaZg3NNngKVBLpOmICv3ovaHOYM0uEkI5yc5QDv5UxWA1uvTEHnnpMDAM7NZP7NUkvaaPND2shifhCNl0DTqCMG/RMXHtM42REmXo/QYemkneX9sjHtFDfUCEsKg1S/2SPI5Gs2womNC8v2ZohXXWSd/rx4JMk/9OTVVdJDSTsawWWF6BGSLW97rZUB1wkQzTMq5WN8bHz+E/XNPIzMyt+O//rHp/0EtTC+bGtCTBIG06t9eyKnQy7X7Xe7pXCYkosgIcPgrgNXti3s7vc/XPfeVlkgBGdSFlIrEm848zaOMI9g9WDSzh0Qd0cvTCptqruD3Ot48aJBhtaeBk5/edugD0aPestKMCL/CrUC4yuHcrUopE8pZny6EZUvHjjPDTN16ND9Qo2vwNpm8g0cgFgV0F0SfvQncMRy2qsvPDI3ttKsTBETqi+yeZrJTtW5NXJTsY2tKN6kY9mKqZQ4AcDzMPR9DQJVGqZXCl3P+8Tt2CDUcP0W0gvnHfCj7YBLrOqPTXPVYHx7BQpGE3JfDacLx33TOOo6MmEcnGVsxTx+udL1QGYznQXk0=